---
apiVersion: v1
kind: Service
metadata:
  name: flask-oidc
spec:
  type: ClusterIP
  selector:
    app: flask-oidc
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-oidc
spec:
  selector:
    matchLabels:
      app: flask-oidc
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-oidc
    spec:
      containers:
        - name: flask-oidc
          image: nickolashkraus/flask-oidc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
